---
title: "tech1wkshp4assign3.1"
author: "Shay Luck"
date: "2024-05-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
library("usethis")
```

#Data sourced from the State of Queensland, Department of Agriculture, Fisheries


```{r}
#get data from Qfish
 library(readxl)
commercial_line <- read_excel("~/Downloads/export-4.xlsx")
View(commercial_line)
#refining data set to exclude total values and 2024 because the data is still incomplete for that year
```


```{r}
head(commercial_line)
```
#Year and Tonnes are characters
#remove comma from Tonnes calues 


```{r}
commercial_line$Tonnes
```

```{r}
comm_line_2023 <-commercial_line |>
  slice(-35:-36) |>
  mutate(Tonnes =  str_replace(Tonnes, pattern = ",", replacement = ""))|>
  mutate_if(is.character, as.double)
head(comm_line_2023)
```



#Creating a basic line plot with Tonnes vs Year
```{r}
ggplot(data = comm_line_2023, mapping = aes(x = CalendarYear, y = Tonnes)) +
  geom_point() +
  geom_line(group = 1) +
  scale_x_continuous(breaks = c(seq(1990, 2023, by = 5))) + 
  scale_y_continuous(breaks = seq(1500, 6500, by = 500)) +
  labs(title = "Yearly Commercial Line Fishery Catch", x = "Year", caption = "Data from the State of Queensland, Department of Agriculture, Fisheries")
```
```{r}
ggplot(
  data = comm_line_2023,mapping = aes(x=CalendarYear , y=Tonnes),)+
  geom_smooth()+
  
  #scale_x_discrete(breaks = seq(1990, 2023, by = 2)) + 
  scale_x_continuous(breaks = c(seq(1990, 2023, by = 5)))+
  scale_y_continuous(breaks = seq(1500, 6500, by = 500)) +
  labs(title = "Yearly Commercial Line Fishery Catch", x = "Year", caption = "Data from the State of Queensland, Department of Agriculture, Fisheries")
  
```


#Trying other graphs 
```{r}
ggplot(data = comm_line_2023, mapping = aes(x = CalendarYear, y = Licences)) +
  geom_point() +
  geom_line(group = 1) +
  scale_x_continuous(breaks = c(seq(1990, 2023, by = 5))) +
  labs(x = "Year")
```

```{r}
#Days with catch reported (unsure of how this metric was calculated, source data not clear)
ggplot(data = comm_line_2023, mapping = aes(x = CalendarYear, y = Days)) +
  geom_point() +
  geom_line(group = 1) +
  scale_x_continuous(breaks = c(seq(1990, 2023, by = 5)))+
  labs(x = "Year")
```

```

